<?php
/**
 *
 * @var Block $block
 * @var Escaper $escaper
 */
use Magento\Catalog\Block\Product\ProductList\Item\Block;
use Magento\Framework\Escaper;
use Magento\Framework\App\ActionInterface;

if ($block->isModuleEnable()!=1) {
    return false;
}
$data = $block->getProducts()->getItems();

$collection = $block->getCollection();
$listProduct = $block->getListProduct();
$iterator = 1;
$image = 'category_page_grid';
$pos = $listProduct->getPositioned();
$helper = $block->getCatalogHelper();
$config = $listProduct->getWidgetCfg();
$showCart = 1;
$enableCompare = 1;
$enableWishlist = 1;
$reviewShow = 0;
$viewMode = 'grid';
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$currency = $block->getCurrency();
/** phpcs:disable */
$allowwislist = $this->helper('Magento\Wishlist\Helper\Data')->isAllow();
/** phpcs:enable */
if (empty($pos)) {$pos = 1;}
?>
<?php if ($data): ?>
    <div class="products wrapper slider-container custom_grid-wrapper content-products">
        <?php $iterator = 1; ?>
        <div class="block-title-tabs">
            <h2 class="title item"><?= /* @noEscape */ $block->getBlockTitle()?></h2>
        </div>
        <ol class="products list items product-items regular slider" id="slider">
            <?php foreach ($data as $_product) { ?>
                <?php if ($_product->getID()): ?>
                    <?php /* @escapeNotVerified */ ?>
                    <?= ($iterator++ == 1) ?
                    '<li class="item product product-item accessory">' : '</li>
                    <li class="item product product-item accessory">'
                    ?>
                    <div class="product-item-info per-product" data-container="product-grid">
                        <?php $productImage = $listProduct->getImage($_product, $image); ?>
                            <?php if ($pos != null): ?>
                                <?php $position = ' style="left:' . $productImage->getWidth() . 'px;' .
                                'top:' . $productImage->getHeight() . 'px;"';
                                ?>
                            <?php endif; ?>
                        <div class="images-container">
                            <?php
                                $_productNameStripped = $listProduct->stripTags($_product->getName(), null, true);
                            ?>
                            <div class="product-hover">
                                <a href="<?= /* @noEscape */$_product->getProductUrl() ?>" 
                                    class="product photo product-item-photo"
                                    tabindex="-1">
                                    <?= /* @noEscape */ $block->getLazyLoadedImage($productImage) ?>
                                </a>
                                <h4 class="product-name product-item-name">
                                    <a class="product-item-link"
                                        href="<?= /* @noEscape */ $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                        <?= /* @noEscape */
                                            $helper->productAttribute(
                                                $_product,
                                                $_product->getName(),
                                                'name'
                                            );
                                        ?>
                                    </a>
                                </h4>
                            </div>
                            <div class="product details product-item-details products-textlink clearfix">
                                <?php
                                $price = '';
                                $type = $_product->getTypeId();
                                if ($type==="configurable") {
                                    $price = $_product->getFinalPrice();
                                } elseif ($type==="simple") {
                                    $price = $_product->getFinalPrice();
                                } elseif ($type==="bundle") {
                                    $price = $_product->getPriceInfo()->getPrice(
                                        'final_price'
                                    )->getMinimalPrice()->getValue();
                                }
                                ?>
                                <span class="price"> <?= /* @noEscape */$currency.number_format($price, 2); ?></span>
                                <?php if ($showCart): ?>
                                    <div class="hover-box clearfix">
                                        <div class="product actions clearfix"
                                        <?= /* @noEscape */ strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                            <?php if ($showCart): ?>
                                                <div class="actions-primary actions-cart 
                                                alotheme-tooltip"
                                                <?= /* @noEscape */ strpos($pos, $viewMode . '-primary') ?
                                                $position : ''; ?>>
                                                    <?php if ($_product->isSaleable()): ?>
                                                        <?php
                                                            $postParams =
                                                            $listProduct->getAddToCartPostParams($_product);
                                                        ?>
                                                        <form data-role="tocart-form"
                                                                action="<?= /* @noEscape */ $postParams['action']; ?>"
                                                                method="post">
                                                            <?php /** phpcs:disable */?>
                                                            <input type="hidden" name="product"
                                                                    value="<?= /* @noEscape */ $postParams['data']['product']; ?>">
                                                            <input type="hidden"
                                                                    name="<?= /* @noEscape */ ActionInterface::PARAM_NAME_URL_ENCODED; ?>"
                                                                    value="<?=/* @noEscape */
                                                                    $postParams['data'][ActionInterface::PARAM_NAME_URL_ENCODED];
                                                                    ?>">
                                                            <?php /** phpcs:enable */?>
                                                            <?php //echo $listProduct->getBlockHtml('formkey') ?>
                                                            <input name="form_key" 
                                                            type="hidden" 
                                                            value="<?= /* @noEscape */ $block->getFormKey();?>">
                                                            <button type="submit"
                                                                    title="
                                                                    <?=$escaper->escapeHtml(__('Add to Cart'));?>
                                                                    "
                                                                    class="action tocart primary button">
                                                                <span>
                                                                    <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                                                                </span>
                                                            </button>
                                                        </form>
                                                    <?php else: ?>
                                                        <?php if ($_product->getIsSalable()): ?>
                                                            <div class="stock available">
                                                                <span>
                                                                    <?= $escaper->escapeHtml(__('In stock')) ?>
                                                                </span>
                                                            </div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable">
                                                                <span>
                                                                    <?= $escaper->escapeHtml(__('Out of stock')) ?>
                                                                </span>
                                                            </div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <?=$reviewShow ? $listProduct->getReviewsSummaryHtml($_product, $templateType):'';?>
                            </div>
                        </div>
                    </div>
                    <?= ($iterator == count($data) + 1) ? '</li>' : '' ?>
                    <?php if (!$listProduct->isRedirectToCartEnabled()):?>
                        <script type="text/x-magento-init">
                        {
                            "[data-role=tocart-form], .form.map.checkout": {
                                "catalogAddToCart": {
                                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                                }
                            }
                        }
                        </script>
                    <?php endif; ?>
                <?php endif; ?>
            <?php } ?>
        </ol>
        <div class="slider-bar" id="sliderBar"></div>
        <button class="prev-button" onclick="prevSlide()"><<</button>
        <button class="next-button" onclick="nextSlide()">>></button>
    </div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "*": {
            "customslider" : {}
        }
    }
</script>